version: '3.8'
services:
  m133-web:
    container_name: m133-web
    build:
      context: ./image
      dockerfile: Dockerfile
    #image: "php:${PHP_VERSION}-apache"
    restart: unless-stopped
    depends_on:
      - m133-db
    volumes:
      - ./HTML/:/var/www/html/
      #- ./conf/httpd/:/etc/apache2/
      #- ./conf/php.ini:/usr/local/etc/php/php.ini
      #- ./log/httpd/:/var/log/apache2/
    networks:
      - traefik
      - backend
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m133-redirect.entrypoints=web"
      - "traefik.http.routers.m133-redirect.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.m133-redirect.middlewares=https-redirect@file"      
      - "traefik.http.routers.m133-redirect.service=noop@internal"
      - "traefik.http.routers.m133.entrypoints=websecure"
      - "traefik.http.routers.m133.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.m133.middlewares=secHeaders@file,m133-redirectregex"
      - "traefik.http.routers.m133.service=m133"
      - "traefik.http.routers.m133.tls=true"
      - "traefik.http.routers.m133.tls.certresolver=letsencrypt"
      - "traefik.http.services.m133.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.m133-redirectregex.redirectregex.regex=^https://([^\\\\/]+)/?$$"
      - "traefik.http.middlewares.m133-redirectregex.redirectregex.replacement=https://$${1}/coming_soon.html"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: "m133-db"
      FQDN: ${FQDN}

  m133-db:
    container_name: m133-db
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    volumes:
      - "./data/mysql/:${MARIADB_DATA_DIR}"
      - "./conf/mysql/:/etc/mysql/"
    networks:
      - backend
    expose:
      - "3306"
    command:
      - "--aria-log-dir-path=${MARIADB_DATA_DIR}"
      - "--datadir=${MARIADB_DATA_DIR}"
    environment:
      TZ: "Europe/Zurich"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  traefik:
    external: true
  backend:
    external: false