version: '3.8'
services:
  m133-web:
    container_name: m133-web
    build:
      context: ./image
      dockerfile: Dockerfile
    #image: "php:${PHP_VERSION}-apache"
    restart: unless-stopped
    depends_on:
      - m133-db
    volumes:
      - ./HTML/:/var/www/html/
      #- /srv/testing/m133/conf/httpd/:/etc/apache2/
      #- /srv/testing/m133/conf/php.ini:/usr/local/etc/php/php.ini
      #- /srv/testing/m133-logs/httpd/:/var/log/apache2/
    networks:
      - m133_frontend
      - m133_backend
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m133-redirect.entrypoints=web"
      - "traefik.http.routers.m133-redirect.rule=Host(`m133.ipoac.ch`)"
      - "traefik.http.routers.m133-redirect.middlewares=https-redirect@file"      
      - "traefik.http.routers.m133-redirect.service=noop@internal"
      - "traefik.http.routers.m133.entrypoints=websecure"
      - "traefik.http.routers.m133.rule=Host(`m133.ipoac.ch`)"
      - "traefik.http.routers.m133.middlewares=secHeaders@file"
      - "traefik.http.routers.m133.service=m133"
      - "traefik.http.routers.m133.tls=true"
      - "traefik.http.routers.m133.tls.certresolver=letsencrypt"
      - "traefik.http.services.m133.loadbalancer.server.port=80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  m133-db:
    container_name: m133-db
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    volumes:
      - "./data/mysql/:${MARIADB_DATA_DIR}"
      - ./conf/mysql/:/etc/mysql/
    networks:
      - m133_backend
    expose:
      - "3306"
    command:
      - "--aria-log-dir-path=${MARIADB_DATA_DIR}"
      - "--datadir=${MARIADB_DATA_DIR}"
    environment:
      TZ: "Europe/Zurich"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  m133_frontend:
    name: proxy
  m133_backend:
    external: false