version: '3.9'
services:
  m133-web:
    container_name: m133-web
    build:
      context: ./build
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - m133-db
    volumes:
      - "../html/:/var/www/html/:ro"
      - "../srv_conf/nginx/:/etc/nginx/:ro"
      - "../srv_conf/php/:/etc/php8/conf.d/:ro"
      - "../srv_conf/php-fpm/:/etc/php8/php-fpm.d/:ro"
      - "../data/log/nginx:/var/log/nginx"
    networks:
      - traefik
      - backend
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m133-redirect.entrypoints=web"
      - "traefik.http.routers.m133-redirect.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.m133-redirect.middlewares=https-redirect@file"      
      - "traefik.http.routers.m133-redirect.service=noop@internal"
      - "traefik.http.routers.m133.entrypoints=websecure"
      - "traefik.http.routers.m133.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.m133.middlewares=secHeaders@file,m133-redirectregex"
      - "traefik.http.routers.m133.service=m133"
      - "traefik.http.routers.m133.tls=true"
      - "traefik.http.routers.m133.tls.certresolver=letsencrypt"
      - "traefik.http.services.m133.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.m133-redirectregex.redirectregex.regex=^https://([^\\\\/]+)/?$$"
      - "traefik.http.middlewares.m133-redirectregex.redirectregex.replacement=https://$${1}/coming_soon.html"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: "m133-db"
      WEBMASTER: ${WEBMASTER}
      FQDN: ${FQDN}

  m133-db:
    container_name: m133-db
    image: "mariadb:${MARIADB_VERSION}"
    restart: always
    volumes:
      - "../data/db/:/var/lib/mysql/"
      - "../srv_conf/mariadb/:/etc/mysql/"
    networks:
      - backend
    expose:
      - "3306"
    command:
      - "--datadir=/var/lib/mysql/"
    environment:
      TZ: "Europe/Zurich"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  traefik:
    external: true
  backend:
    external: false
    internal: true